galaxy_info:
  author: Vlada Borisova
  role_name: deploy
  description: Deploy Turbokotiki website using Docker
  min_ansible_version: 2.12

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

dependencies: []